title: "S-PRESSO: Ultra Low Bitrate Sound Effect Compression With Diffusion Autoencoders And Offline Quantization"
github: [metadata]

remote_theme: pages-themes/cayman@v0.2.0
url: "https://zineblahrichi.github.io"
baseurl: "/s-presso"

# local testing
# baseurl: ""
# repository: "s-presso"

markdown: kramdown
kramdown:
    math_engine: katex
    syntax_highlighter: rougify

plugins:
    - jekyll-remote-theme
